name: rotaract
description: "Rotaract Club"
publish_to: 'none' 
version: 1.0.3+3

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  firebase_crashlytics: ^4.1.1
  cloud_functions: ^5.1.1
  uuid: ^4.5.0
  firebase_ui_auth: ^1.15.0
  lottie: ^3.1.2
  firebase_storage: ^12.3.0
  share_plus: ^10.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7
  # qr_code_scanner: ^1.0.1
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  # csv: ^6.0.0
  image_picker: ^1.1.2
  # cached_network_image: ^3.4.1
  image_network: ^2.6.0
  extended_image: ^10.0.1
  cached_network_image: ^3.4.1
  file_picker: ^10.1.9
  video_player: ^2.10.0
  flutter_linkify: ^6.0.0
  table_calendar: ^3.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.0
flutter:  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/csv/
